version: '2'
services:
  mysql:
    image: mysql:5.7
    command:
      - '--server-id=1'
      - '--log-bin=/var/lib/mysql/mysql-bin.log'
      - '--binlog-format=ROW'
      - '--sync-binlog=100'
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    volumes:
      - /var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "3301:3306"
